title: "NAIRR Teaching Innovation Accelerator"
description: "Course-building accelerator for instructors, hosted by Morehouse College's Center for Broadening Participation."
markdown: kramdown
baseurl: "/nairr-teaching-innovation"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
